version: '2'
services:
  opentsdb:
    container_name: opentsdb
    image: petergrace/opentsdb-docker:latest
    ports:
        - 4242:4242
  jupyter_spark:
    image: jupyter/all-spark-notebook
    ports:
        - 8888:8888
    command: jupyter/base-notebook start-notebook.sh --NotebookApp.password='sha1:61c254b07ae6:ca68942bf64da7e00f9ad9ea2ed89a51997df512'
