version: '2'
services:
  opentsdb:
    container_name: opentsdb
    image: petergrace/opentsdb-docker:latest
    ports:
        - 4242:4242
  jupyter_spark:
    image: jupyter/all-spark-notebook
    ports:
        - 8888:8888
